name: Python package

on: [push]

jobs:
  build:
<<<<<<< HEAD

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
=======
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
>>>>>>> Adds github ci workflow
    - name: Install tox
      run: pip install tox
    - name: Run tox
      run: python -m tox
